#' Scrape results from parkrun
#' 
#' Reads the table of results from http://www.parkrun.org.uk/`eventName`/results/weeklyresults/?runSeqNumber=`runSeqNumber`
#' and returns the output as an array.
#' 
#' @param eventName Name of the event, taken from the URL (see details).
#' @param runSeqNumber Integer specifying the event number (see details).
#' 
#' @return An array corresponding to the HTML table on the page requested
#' 
#' @author Martin R. Smith
#' 
#' @importFrom RCurl getURL
#' @export
ScrapeResults <- function(eventName, runSeqNumber) {
  
  ParseCell <- function(expression, string, perl=FALSE) {
    ifelse(string == '/>' | string == ">Unknown</td>", NA, sub(expression, "\\1", string, perl=perl))
  }
  
  url <- paste0("http://www.parkrun.org.uk/", eventName, "/results/weeklyresults/?runSeqNumber=", runSeqNumber)
  html <- getURLContent(url)
  resultsTable <- strsplit(strsplit(html, '<tbody', fixed=TRUE)[[1]][2], '</tbody>', fixed=TRUE)[[1]][1]
  tableRows <- strsplit(strsplit(resultsTable, "<tr>", fixed=TRUE)[[1]][-1], '</tr>', fixed=TRUE)
  # columnNames <- strsplit(tableRows[[1]][1], "(?:</?th/?>)*</?th[^>.]*?>", perl=TRUE)[[1]][-1]
  tableCells <- vapply(tableRows, function(row) unlist(strsplit(row, '<td', fixed=TRUE)), character(12))
  
  times <- ParseCell(">([\\d\\:]+)</td>", tableCells[4, ], perl=TRUE)
  # From https://stackoverflow.com/questions/10835908:
  timeInSeconds <- as.numeric(as.POSIXct(strptime(times, format = "%M:%OS"))) - 
                as.numeric(as.POSIXct(strptime("0", format = "%S")))
  
  data.frame (
    eventName = eventName,
    runSeqNumber = runSeqNumber,
    pos = as.integer(ParseCell(".*>(\\d+)</td>", tableCells[2, ])),
    athleteNumber = as.integer(ParseCell(".*athleteNumber\\=(\\d+)\".*", tableCells[3, ])),
    time = times,
    timeInSeconds = timeInSeconds,
    ageCat = ParseCell(".*ageCat=(.*)\".*</td>", tableCells[5, ]),
    ageGrade = as.numeric(ParseCell(">(.*) %</td>", tableCells[6, ])),
    gender = ParseCell(">(.)</td>", tableCells[7, ]),
    genderPos = as.numeric(ParseCell(">(\\d*)</td>", tableCells[8, ])),
    note = ParseCell(">(.*)</td>", tableCells[10, ]),
    totalRuns = as.integer(ParseCell(">(\\d*)</td>", tableCells[11, ]))
  )
}

#' Obtain parkrun results from cache, scraping if not available
#' @inheritParams ScrapeResults
#' 
#' @author Martin R. Smith
#' @export
GetResults <- function (eventName, runSeqNumber) {
  
  eventDir <- paste0(sub("(.*parkrun).*", "\\1", getwd()), '/results/', eventName)
  eventFile <- paste0(eventDir, '/', runSeqNumber, '.txt')
  
  if (file.exists(eventFile)) {
    # Return: 
    read.table(eventFile)
  } else {
    results <- ScrapeResults(eventName, runSeqNumber)
    Sys.sleep(runif(1) * 12) # Be polite and avoid overloading server
    if (!dir.exists(eventDir)) dir.create(eventDir)
    write.table(results, eventFile)
    
    # Return: 
    results
  }
}

#' Summarise parkrun results
#' 
#' @param results Data frame of results, perhaps generated by [ScrapeResults]
#' @param athlete Integer vector specifying athlete(s) whose speeds should be indicated on the plot
#' 
#' @author Martin R. Smith
#' @export
SummariseResults <- function (results, athlete=NA) {
  attach(results)
  on.exit(detach(results))
  
  male <- ifelse(is.na(gender), FALSE, gender == 'M')
  female <- ifelse(is.na(gender), FALSE, gender == 'F')
  
  maleTimes <- timeInSeconds[male]
  femaleTimes <- timeInSeconds[female]
  
  maleSpeeds <- 5000 / maleTimes
  femaleSpeeds <- 5000 / femaleTimes
  
  shapiro.test(maleSpeeds)
  shapiro.test(femaleSpeeds)
  
  maleCol <- "#6688dd"
  femaleCol <- "#eeaa66"
  
  breakSize <- 0.25
  breaks <- seq(min(c(maleSpeeds, femaleSpeeds)) - breakSize, max(maleSpeeds) + breakSize, by=breakSize)

  maleHist <- hist(maleSpeeds, breaks=breaks, plot=FALSE)
  femaleHist <- hist(femaleSpeeds, breaks=breaks, plot=FALSE)
  
  
  plot.new()
  plot.window(xlim=range(breaks), ylim=range(c(maleHist$counts, femaleHist$counts)))
  axis(1)
  mtext("Speed (m/s)", 1, line=2)
  axis(2)
  mtext("Athletes", 2, line=2)
  
  plot(maleHist, col=paste0(maleCol, '88'), add=TRUE)
  plot(femaleHist, col='#eeaa6688', add=TRUE)

  abline(v=mean(maleSpeeds), col=maleCol, lty=2)
  curve(max(maleHist$counts) * dnorm(x, mean(maleSpeeds), sd(maleSpeeds)),
        min(maleSpeeds), max(maleSpeeds), add=T, col=maleCol)
  
  abline(v=mean(femaleSpeeds), col=femaleCol, lty=2)
  curve(max(femaleHist$counts) * dnorm(x, mean(femaleSpeeds), sd(femaleSpeeds)),
        min(femaleSpeeds), max(femaleSpeeds), add=T, col=femaleCol)
  
  
  myAthlete <- ifelse(is.na(athleteNumber), FALSE, athleteNumber %in% athlete)
  if (any(myAthlete)) {
    abline(v = 5000 / timeInSeconds[myAthlete], col='#228835', lwd=2)
  }
  
}


